# https://certbot.eff.org/docs/using.html
- name: '{{ ansible_os_family }} playbook: provision.'
  include: '{{ ansible_os_family }}/certbot-provision.yml'

# 10 Signed certs per floating week | https://letsencrypt.org/docs/rate-limits/
- name: 'Certbot gets Signed cert using webroot'
  command: >
    certbot certonly
    --webroot
    --webroot-path  {{ acme_challenge_path }}
    --non-interactive
    --agree-tos
    --expand
    --preferred-challenges http
    --email '{{ subj.email }}'
    --domains "{{ item.domains | join(', ') }}"
  tags: certbot
  with_items: '{{ services }}'
  args:
    creates: '{{ certbot.home }}/live/{{ item.domains[0] }}/fullchain.pem'
