- name: '{{ ansible_os_family }} playbook: provision.'
  include: '{{ ansible_os_family }}/provision.yml'
  notify: Start nginx

- name: '{{ ansible_os_family }} variables: included.'
  include_vars: '{{ ansible_os_family }}.yml'
  tags: certbot

- name: 'Diffie-Hellman {{ crypt.dhparam }} bit: {{ ssl.dhparam }}'
  command: openssl dhparam -out {{ ssl.dhparam }} {{ crypt.dhparam }}
  args:
    creates: '{{ ssl.dhparam }}'

- name: 'Nginx configuration for ACME challange deployed'
  include: acme.yml

- name: 'TLS for domains: {{ services|map(attribute="domains")|join(" ") }}'
  include: '{{ method | default ("certbot") }}.yml'

- name: Deploying new configuration
  include: '{{ ansible_os_family }}/conf.yml'
  with_items: '{{ services }}'
  notify: Reload nginx

- name: Robots.txt deployed
  copy:
    content: '{{ robots }}'
    dest: '{{ acme_challenge_path }}/robots.txt'
  tags: config
  when: robots_content is defined
  notify:
  - reload nginx
  - reload uwsgi

- name: Test nginx before handlers are flushed
  command: nginx -t
