- name: '{{ ansible_os_family }} YUM: EPEL repository enabled'
  yum:
    name: epel-release
  tags: packages
  
- name: '{{ ansible_os_family }} YUM: provision'
  yum:
    name: nginx,certbot
  tags: packages
